### ISSUE TITLE
Compiler Bug?

### ISSUE THREAD

**Issue by drewdahlke** [elastic/elasticsearch-lang-mvel#11]
Running on 2.4.1 I periodically see these messages get logged. This script gets used over 100 times/sec and for the most part it works, but it logs this out maybe once an hour. Our script is the same every time we use it. 

Expression: for (entry : conversation.entrySet()) {    if (entry.key != "segments") {        ctx._source[entry.key] = entry.value;    }}segmentExists = 0;for (existingSrc : ctx._source.entrySet()) {    if (existingSrc.key == "segments") {        segmentExists = 1;    }}for (int i = 0; i < conversation.segments.size(); i++) {    match = -1;    if (segmentExists == 0) {		ctx._source.segments = conversation.segments;    } else {		for (int j = 0; match == -1 && j < ctx._source.segments.size()
; j++) {	        if (ctx._source.segments[j].segmentId == conversation.segments[i].segmentId) {	            match = j;	        }	    }	    if (match == -1) {	        ctx._source.segments += conversation.segments[i];	    } else {	        foreach (entry : conversation.segments[i].entrySet()) {	            ctx._source.segments[match][entry.key] = entry.value;	        }	    }    }}
**** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/mvel2

**Comment by dadoonet** [comment]
Are you using the exact same script without changing any parameter?

Asking that because the script is supposed to be compiled once and only once per node if it does no change.

BTW, mvel is not supported anymore from 2.0. You should consider another scripting language: https://www.elastic.co/guide/en/elasticsearch/plugins/master/scripting.html
